In [17]:
import numpy as np
a = np.ones([5,5])
b = np.zeros([3,3])
b[1,1] = 9
a[1:4,1:4] = b
print(a)
print(a[[0,3,4],3:])

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1.]
 [0. 1.]
 [1. 1.]]


In [20]:
print(a[[1,2],[1,2]])

[0. 9.]
